import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect } from "react";
import { IncomeTable } from "@/views/IncomeTable";
import { ExpenseTable } from "@/views/ExpenseTable";
import { Settings } from "@/views/Settings";
import { CalcsTable } from "@/views/CalcsTable";
import { fetchDataFx } from "@/effects/getDataFx";

export default function Home() {
  useEffect(() => {
    fetchDataFx()
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{ display: 'flex', flexDirection: 'row', columnGap: '16px' }}>
          <IncomeTable />
          <ExpenseTable />
        </div>
        <Settings />
        <CalcsTable />
      </main>
    </>
  );
}
