import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import axios from "axios";
import { ParsedBudgetEntry, ParsedConstantMoneyMove } from "../types";
import { parseCalcs } from "../utils/parseCalcs";
import { parseIncomes } from "../utils/parseIncomes";
import { parseExpenses } from "../utils/parseExpenses";
import { calculateBudget } from "../utils/utils";
import { baseUrl } from "../constants";
import { IncomeTable } from "@/views/IncomeTable";
import { ExpenseTable } from "@/views/ExpenseTable";
import { Settings } from "@/views/Settings";
import { CalcsTable } from "@/views/CalcsTable";

export default function Home() {
  const [calcs, setCalcs] = useState<ParsedBudgetEntry[]>([]);
  const [incomes, setIncomes] = useState<ParsedConstantMoneyMove[]>([]);
  const [expenses, setExpenses] = useState<ParsedConstantMoneyMove[]>([]);

  useEffect(() => {
    async function get() {
      const res = await axios.get(baseUrl);
      const parsedCalcs = parseCalcs(res.data.calcs);
      const parsedIncomes = parseIncomes(res.data.income);
      const parsedExpenses = parseExpenses(res.data.expense);

      setIncomes(parsedIncomes);
      setExpenses(parsedExpenses);
      const calculatedCalcs = calculateBudget(
        parsedCalcs,
        parsedIncomes,
        parsedExpenses,
        0
      );
      setCalcs(calculatedCalcs);
    }
    get();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <IncomeTable incomes={incomes} setIncomes={setIncomes} /> 
        <ExpenseTable expenses={expenses} setExpenses={setExpenses} />
        <Settings incomes={incomes} expenses={expenses} calcs={calcs} setCalcs={setCalcs} />
        <CalcsTable calcs={calcs} setCalcs={setCalcs} /> 
      </main>
    </>
  );
}
