import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import axios from 'axios'
import { Table } from './components/Table'

const inter = Inter({ subsets: ['latin'] })
const url = 'https://script.google.com/macros/s/AKfycbwnvwyuUfil4NtQlAKdagrz6EJijWi88rpU9Ou1f9myqWWk65TVjKQ57VtLYm3Qsby7fg/exec'
export default function Home() {
  const [calcs, setCalcs] = useState<string[][]>([])
  const [incomes, setIncomes] = useState<string[][]>([])
  const [expenses, setExpenses] = useState<string[][]>([])
  useEffect(() => {
    async function get() {
      const res = await axios.get(url);
      setCalcs(res.data.calcs);
      setIncomes(res.data.income);
      setExpenses(res.data.expense);
    }
    get()
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {calcs?.length ? <Table data={calcs} /> : null}
        {incomes?.length ? <Table data={incomes} /> : null}
        {expenses?.length ? <Table data={expenses} /> : null}
      </main>
    </>
  )
}
